-- MySQL Script generated by MySQL Workbench
-- Thu Nov 24 21:50:55 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema EDS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema EDS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `EDS` DEFAULT CHARACTER SET utf8 ;
USE `EDS` ;

-- -----------------------------------------------------
-- Table `EDS`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EDS`.`Profesor` (
  `idProfesor` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `identificacion` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProfesor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EDS`.`Area`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EDS`.`Area` (
  `idArea` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idArea`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EDS`.`Institucion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EDS`.`Institucion` (
  `idInstitucion` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `director` VARCHAR(45) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `logo` VARCHAR(45) NOT NULL COMMENT 'Es un link que lleva a una imagen, se guarda sólo la URL.',
  `lema` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`idInstitucion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EDS`.`Grupo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EDS`.`Grupo` (
  `idGrupo` INT NOT NULL,
  `idInstitucion` INT NOT NULL,
  `nivel` INT NOT NULL,
  `subnivel` VARCHAR(1) NOT NULL,
  `anno` YEAR NOT NULL,
  `estado` VARCHAR(10) BINARY NOT NULL COMMENT 'Activo o inactivo. Los inactivos se mantendrán para preservar un historial.',
  PRIMARY KEY (`idGrupo`, `idInstitucion`),
  INDEX `idInstitucion_idx` (`idInstitucion` ASC) VISIBLE,
  CONSTRAINT `Grupo_Institucion`
    FOREIGN KEY (`idInstitucion`)
    REFERENCES `EDS`.`Institucion` (`idInstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EDS`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EDS`.`Curso` (
  `idCurso` INT NOT NULL,
  `idArea` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `idProfesor` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `posicion` INT NOT NULL,
  `porcentaje` INT NOT NULL,
  PRIMARY KEY (`idCurso`),
  INDEX `idProfesor_idx` (`idProfesor` ASC) VISIBLE,
  INDEX `idArea_idx` (`idArea` ASC) VISIBLE,
  INDEX `idGrupo_idx` (`idGrupo` ASC) VISIBLE,
  CONSTRAINT `Curso_Profesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `EDS`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Curso_Area`
    FOREIGN KEY (`idArea`)
    REFERENCES `EDS`.`Area` (`idArea`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Curso_Grupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `EDS`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EDS`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EDS`.`Estudiante` (
  `idEstudiante` INT NOT NULL,
  `idInstitucion` INT NOT NULL,
  `idGrupo` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `docIdentidad` INT(10) NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `telefono` INT(20) NOT NULL,
  `acudiente` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) BINARY NOT NULL DEFAULT 'activo',
  `diaNacimiento` DATE NOT NULL,
  `madre` VARCHAR(45) NULL,
  `padre` VARCHAR(45) NULL,
  PRIMARY KEY (`idEstudiante`),
  INDEX `idInstitucion_idx` (`idInstitucion` ASC) VISIBLE,
  INDEX `idGrupo_idx` (`idGrupo` ASC) VISIBLE,
  CONSTRAINT `Estudiante_Institucion`
    FOREIGN KEY (`idInstitucion`)
    REFERENCES `EDS`.`Institucion` (`idInstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Estudiante_Grupo`
    FOREIGN KEY (`idGrupo`)
    REFERENCES `EDS`.`Grupo` (`idGrupo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EDS`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EDS`.`Admin` (
  `idAdmin` INT NOT NULL,
  `idInstitucion` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `identificacion` VARCHAR(45) NOT NULL,
  `tipoIdentificacion` VARCHAR(45) NOT NULL,
  `telefono` INT(20) NOT NULL,
  PRIMARY KEY (`idAdmin`),
  INDEX `idInstitucion_idx` (`idInstitucion` ASC) VISIBLE,
  CONSTRAINT `Admin_Institucion`
    FOREIGN KEY (`idInstitucion`)
    REFERENCES `EDS`.`Institucion` (`idInstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `EDS`.`InstitucionXProfesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EDS`.`InstitucionXProfesor` (
  `idInstitucion` INT NOT NULL,
  `idProfesor` INT NOT NULL,
  PRIMARY KEY (`idInstitucion`, `idProfesor`),
  INDEX `idProfesor_idx` (`idProfesor` ASC) VISIBLE,
  CONSTRAINT `InstitucionXProfesor_Institucion`
    FOREIGN KEY (`idInstitucion`)
    REFERENCES `EDS`.`Institucion` (`idInstitucion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `InstitucionXProfesor_Profesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `EDS`.`Profesor` (`idProfesor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
